Pod # Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IKIER

  pod 'SnapKit'
  pod 'Alamofire' , '~> 5.8.1'
  pod 'SDWebImage', '~> 4.0.0'
  end
  

